management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaserver:8070/eureka/}
