server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"

address:
  defaultBranchAddress: "123 Main St, Anytown, USA"