services:

  network-deploy-service:
    networks:
      - bank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  # 🔥 Config Server özel konfigürasyonu
  microservice-configserver-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: git       # ❗ zorunlu — configserver git modunda çalışacak
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/nisanurgunes/Microservice-BankApplication.git"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: "config-repo"
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: new-master
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"
      SPRING_CLOUD_CONFIG_SERVER_GIT_FORCE_PULL: "true"
