version: "3.8"

services:

  # 1) Accounts DB
  accountsdb:
    container_name: accountsdb-prod
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  # 2) Cards DB
  cardsdb:
    container_name: cardsdb-prod
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  # 3) Loans DB
  loansdb:
    container_name: loansdb-prod
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config


  # 4) CONFIG SERVER
  configserver:
    image: gunesng022/configserver:docker
    container_name: configserver-ms-prod
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    ports:
      - "8072:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s


  # 5) ACCOUNTS SERVICE
  accounts:
    image: gunesng022/accounts
    container_name: accounts-ms-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config


  # 6) LOANS SERVICE
  loans:
    image: gunesng022/loans
    container_name: loans-ms-prod
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config


  # 7) CARDS SERVICE
  cards:
    image: gunesng022/cards
    container_name: cards-ms-prod
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  bank:
    driver: bridge
